# Site settings
title: Daniel's Blog
header-img: img/home-bg.jpg
email: boylinshan@163.com
copyright_name: 
description: ""
baseurl: ""
url: "http://yourdomain.com"
twitter_username: 
github_username: boylinshan
facebook_username:  
email_username: boylinshan@163.com 

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
